import React,{useState} from 'react';
import {ArrowUpRight,ChevronDown} from 'lucide-react';
import type {Lang} from './data';
type Client={name:string;description:string;logoUrl?:string};
export default function ClientStories({lang,clients}:{lang:Lang;clients:Client[]}){
 const en=lang==='en';const displayName=(name?:string)=>name==='קבוצת תדהר'?'קבוצת תדהר · מחלקת FP&A':name==='Tidhar Group'?'Tidhar Group · FP&A department':name;const [active,setActive]=useState(0);
 const indices=(en?['Tidhar Group','Institute of Certified Public Accountants in Israel','Pango','Fetcherr','UVision']:['קבוצת תדהר','לשכת רואי החשבון בישראל','פנגו','Fetcherr','UVision']).map(name=>clients.findIndex(c=>c.name===name)).filter(i=>i>=0);const selected=clients[indices[active]];
 const description=selected?.description||(en?'One of the organizations we have worked with.':'בין הארגונים שעבדו איתנו.');const sentenceEnd=description.indexOf('. ');const lead=sentenceEnd>0?description.slice(0,sentenceEnd+1):description;const more=sentenceEnd>0?description.slice(sentenceEnd+2):'';
 const labels=en?['From learning to daily practice','A profession looking ahead','From a workshop to a workflow','Fetcherr','UVision']:['מלמידה לעבודה בצוות','מקצוע שמסתכל קדימה','מסדנה לתהליך עבודה','Fetcherr','UVision'];
 const formats=en?['TEAM × PRACTICE','PROFESSION × POSSIBILITY','FINANCE × TECHNOLOGY','FINANCE × AI','PEOPLE × PRACTICE']:['צוות × עשייה','מקצוע × אפשרויות','פיננסים × טכנולוגיה','פיננסים × AI','אנשים × עשייה'];
 return <section className="af-client-stories" aria-labelledby="client-stories-title"><div className="af-wrap"><div className="af-stories-heading"><span className="af-label">{en?'IN GOOD COMPANY':'בחברה טובה'}</span><h2 id="client-stories-title">{en?'Different organizations.\nA shared curiosity.':'ארגונים שונים.\nסקרנות משותפת.'}</h2><p>{en?'A few moments from our work with finance teams and professional communities.':'כמה דוגמאות מהמפגשים שלנו עם צוותי כספים וקהילות מקצועיות.'}</p></div><div className="af-client-story-layout"><div className="af-client-select" role="group" aria-label={en?'Choose an organization':'בחירת ארגון'}>{indices.map((n,i)=><button key={clients[n].name} aria-pressed={active===i} onClick={()=>setActive(i)}><span className="af-client-index">0{i+1}</span><span>{displayName(clients[n].name)}</span><ArrowUpRight size={24}/></button>)}</div><div className="af-client-story" aria-live="polite" key={active}><div className="af-story-lines" aria-hidden="true"><i/><i/><i/></div><span className="af-kicker">{formats[active]}</span><h3>{labels[active]}</h3><p>{lead}</p>{more&&<details className="af-read-more"><summary>{en?'More about the session':'עוד על המפגש'}</summary><p>{more}</p></details>}<span className="af-story-signature">AI FINANCE <span>×</span> {displayName(selected?.name)}</span></div></div><details className="af-more-clients"><summary>{en?'More organizations we have worked with':'עוד ארגונים שפגשנו בדרך'}<ChevronDown size={18}/></summary><div className="af-client-directory">{clients.filter((_,i)=>!indices.includes(i)).map(c=><div key={c.name}><strong>{c.name}</strong>{c.description&&<p>{c.description}</p>}</div>)}</div></details></div></section>
}
