import React,{useEffect,useRef,useState} from 'react';
import {Play} from 'lucide-react';
import type {Lang} from './data';
import ConferenceTalk from './ConferenceTalk';
import transcripts from './film-transcripts.json';
const films=[{id:'tal-live-demo',he:'הדגמה חיה מול הקהל',en:'A live demonstration on stage',heText:'טל מציגה תהליך ניתוח בזמן ההרצאה. קטע מוקלט מתוך הדגמה, לא נתוני שוק עדכניים.',enText:'Tal presents an analysis workflow during a talk. A recorded demonstration, not current market data.',duration:12},{id:'tal-audience',he:'מהדאשבורד לשאלה העסקית',en:'From a dashboard to a business question',heText:'טל מצביעה על חריגות בדאשבורד ומחברת אותן לשאלת הגבייה. קטע מתוך הרצאה.',enText:'Tal points out dashboard exceptions and connects them to collections. An excerpt from a talk.',duration:10},{id:'tal-stage',he:'טל על הבמה',en:'Tal on stage',heText:'מתחילים משאלה עסקית: איך מוצאים לקוחות חדשים? קטע מתוך הרצאה בכנס רואי החשבון.',enText:'Starting with a business question: how do we find new clients? An excerpt from an accountants’ conference.',duration:5},{id:'roei-session',he:'רועי עם הצוות',en:'Roei with the team',heText:'לא נשארים לבד מול הכלי. רועי וטל מלווים את ההתנסות ועוזרים כשמשהו לא עובד.',enText:'You are not left alone with the tool. Roei and Tal guide the practice and help when something does not work.',duration:7},{id:'workshop-room',he:'הלמידה מסביב לשולחן',en:'Learning around the table',heText:'הצצה למפגש מקצועי מתוך החומרים שלנו.',enText:'A glimpse into one of our professional sessions.',duration:14}];
function Film({film,lang}:{film:typeof films[number];lang:Lang}){const en=lang==='en';const [started,setStarted]=useState(false);const ref=useRef<HTMLVideoElement>(null);
 useEffect(()=>{const video=ref.current;if(!video)return;const observer=new IntersectionObserver(([entry])=>{if(!entry.isIntersecting)video.pause()},{threshold:.1});observer.observe(video);const hide=()=>{if(document.hidden)video.pause()};document.addEventListener('visibilitychange',hide);return()=>{observer.disconnect();document.removeEventListener('visibilitychange',hide)}},[started]);
 return <article className={`af-film ${film.id!=='tal-stage'?'af-film-portrait':''}`}><div className="af-film-screen">{started?<video ref={ref} controls autoPlay playsInline preload="none" poster={`/media/${film.id}.jpg`} aria-label={film[lang]}><source src={`/media/${film.id}-sound.mp4`} type="video/mp4"/><track kind="captions" src={`/media/${film.id}.he.vtt`} srcLang="he" label="עברית" default={!en}/><track kind="subtitles" src={`/media/${film.id}.en.vtt`} srcLang="en" label="English" default={en}/><a href={`/media/${film.id}-sound.mp4`}>{en?'Open video':'פתיחת הסרטון'}</a></video>:<button onClick={()=>setStarted(true)} aria-label={`${en?'Play':'הפעלת הסרטון'}: ${film[lang]}`}><img src={`/media/${film.id}.jpg`} alt={film[lang]} loading="lazy"/><span className="af-film-play"><Play size={22} fill="currentColor"/></span><span className="af-film-duration">{film.duration} {en?'SEC':'שניות'}</span></button>}</div><div className="af-film-caption"><h3>{film[lang]}</h3><p>{en?film.enText:film.heText}</p><details className="af-film-transcript"><summary>{en?'Read the transcript':'לקריאת התמלול'}</summary><p>{transcripts[film.id as keyof typeof transcripts][lang]}</p></details></div></article>
}
export default function EventFilms({lang,selection,fullTalk=false}:{lang:Lang;selection?:string[];fullTalk?:boolean}){const en=lang==='en';return <section className="af-section af-event-films" id="films"><div className="af-wrap"><div className="af-section-heading"><div><div className="af-label">{en?'A FEW SECONDS IN THE ROOM':'כמה שניות בתוך החדר'}</div><h2>{en?'This is what it looks like.':'ככה זה נראה באמת.'}</h2></div><p>{en?'Original excerpts from our talks and workshops, with the sound from the room. Audio is in Hebrew. Press play to watch and listen.':'קטעים מקוריים מההרצאות והסדנאות שלנו, עם הסאונד מהחדר. לחצו לצפייה ולהאזנה.'}</p></div>{fullTalk&&<ConferenceTalk lang={lang}/>}<div className={`af-film-grid ${selection?.length===1?'af-film-single':''}`}>{films.filter(f=>!selection||selection.includes(f.id)).map(f=><Film key={f.id} film={f} lang={lang}/>)}</div></div></section>}
