import React,{useEffect,useRef,useState} from 'react';
import {Play,ArrowUpRight} from 'lucide-react';
import type {Lang} from './data';
const films=[{id:'tal-stage',he:'טל על הבמה',en:'Tal on stage',heText:'רגע מתוך הרצאה בכנס רואי החשבון.',enText:'A moment from a talk at an accountants’ conference.',duration:9},{id:'roei-session',he:'רועי עם הצוות',en:'Roei with the team',heText:'הדגמה, שאלות ועבודה משותפת בחדר.',enText:'Demonstration, questions and working together.',duration:7},{id:'workshop-room',he:'הלמידה מסביב לשולחן',en:'Learning around the table',heText:'הצצה למפגש מקצועי מתוך החומרים שלנו.',enText:'A glimpse into one of our professional sessions.',duration:10}];
function Film({film,lang}:{film:typeof films[number];lang:Lang}){const en=lang==='en';const [started,setStarted]=useState(false);const ref=useRef<HTMLVideoElement>(null);
 useEffect(()=>{const video=ref.current;if(!video)return;const observer=new IntersectionObserver(([entry])=>{if(!entry.isIntersecting)video.pause()},{threshold:.1});observer.observe(video);const hide=()=>{if(document.hidden)video.pause()};document.addEventListener('visibilitychange',hide);return()=>{observer.disconnect();document.removeEventListener('visibilitychange',hide)}},[started]);
 return <article className="af-film"><div className="af-film-screen">{started?<video ref={ref} controls autoPlay muted playsInline preload="none" poster={`/media/${film.id}.jpg`} aria-label={film[lang]}><source src={`/media/${film.id}.mp4`} type="video/mp4"/><a href={`/media/${film.id}.mp4`}>{en?'Open video':'פתיחת הסרטון'}</a></video>:<button onClick={()=>setStarted(true)} aria-label={`${en?'Play':'הפעלת הסרטון'}: ${film[lang]}`}><img src={`/media/${film.id}.jpg`} alt={film[lang]} loading="lazy"/><span className="af-film-play"><Play size={22} fill="currentColor"/></span><span className="af-film-duration">{film.duration} {en?'SEC':'שניות'}</span></button>}</div><div className="af-film-caption"><h3>{film[lang]}</h3><p>{en?film.enText:film.heText}</p></div></article>
}
export default function EventFilms({lang}:{lang:Lang}){const en=lang==='en';return <section className="af-section af-event-films" id="films"><div className="af-wrap"><div className="af-section-heading"><div><div className="af-label">{en?'A FEW SECONDS IN THE ROOM':'כמה שניות בתוך החדר'}</div><h2>{en?'This is what it looks like.':'ככה זה נראה באמת.'}</h2></div><p>{en?'Short visual excerpts from our talks and workshops. Edited without sound. Press play to take a look.':'קטעים קצרים מההרצאות והסדנאות שלנו, בעריכה ללא קול. לחצו לצפייה.'}</p></div><div className="af-film-grid">{films.map(f=><Film key={f.id} film={f} lang={lang}/>)}</div></div></section>}
