import React,{useEffect,useRef,useState} from 'react';
import {Play,Pause,RotateCcw,Download,Check,FileSpreadsheet,Search,ChartNoAxesCombined,ShieldCheck,Bot,ArrowUpRight} from 'lucide-react';
import type {Lang} from './data';
const records=[
 {id:'C-101',type:'clients',he:'לקוח אלפא',en:'Client Alpha',total:48,paid:32,late:true},
 {id:'C-102',type:'clients',he:'לקוח בטא',en:'Client Beta',total:36,paid:24,late:false},
 {id:'C-103',type:'clients',he:'לקוח גמא',en:'Client Gamma',total:28,paid:16,late:true},
 {id:'C-104',type:'clients',he:'לקוח דלתא',en:'Client Delta',total:16,paid:8,late:false},
 {id:'S-201',type:'suppliers',he:'ספק מערכות',en:'Systems supplier',total:34,paid:20,late:false},
 {id:'S-202',type:'suppliers',he:'ספק שירותים',en:'Services supplier',total:26,paid:18,late:true},
 {id:'S-203',type:'suppliers',he:'ספק תפעול',en:'Operations supplier',total:20,paid:14,late:false},
 {id:'S-204',type:'suppliers',he:'ספק ציוד',en:'Equipment supplier',total:14,paid:8,late:false}
];
const starts=[0,4200,8500,13000];
const receivables=records.filter(r=>r.type==='clients').reduce((n,r)=>n+r.total-r.paid,0);
const payables=records.filter(r=>r.type==='suppliers').reduce((n,r)=>n+r.total-r.paid,0);
export default function FinanceMoment({lang}:{lang:Lang}){
 const en=lang==='en';const [time,setTime]=useState(18000),[playing,setPlaying]=useState(false),[reduced,setReduced]=useState(false),[selected,setSelected]=useState('C-101'),[collection,setCollection]=useState(100),[tab,setTab]=useState('clients'),[checks,setChecks]=useState([true,true,true,false,false]);
 const host=useRef<HTMLElement>(null);const stage=time<4200?0:time<8500?1:time<13000?2:3;
 const labels=en?['Ask','Reconcile','Dashboard','Month close']:['שואלים','מתאימים','דאשבורד','סוגרים חודש'];
 const prompt=en?'Prepare a month-end dashboard from the customer and supplier ledgers. Reconcile balances, flag overdue items and show how collections affect cash flow.':'הכינו דאשבורד לסגירת חודש מתוך כרטסות הלקוחות והספקים. התאימו יתרות, סמנו חובות באיחור והציגו איך הגבייה תשפיע על התזרים.';
 const collected=receivables*collection/100,net=collected-payables,focus=records.find(r=>r.id===selected)!;
 const visible=records.filter(r=>r.type===tab),progress=checks.filter(Boolean).length*20;
 const tasks=en?['Customer balances reconciled','Supplier balances reconciled','Overdue items flagged','Review exceptions with owners','Approve the closing package']:['התאמת יתרות לקוחות','התאמת יתרות ספקים','סימון יתרות באיחור','בדיקת החריגים עם האחראים','אישור חבילת הסגירה'];
 const f=(n:number)=>new Intl.NumberFormat(en?'en-US':'he-IL',{maximumFractionDigits:1}).format(n);
 useEffect(()=>{const media=matchMedia('(prefers-reduced-motion: reduce)');const update=()=>{setReduced(media.matches);if(media.matches)setPlaying(false)};update();media.addEventListener('change',update);return()=>media.removeEventListener('change',update)},[]);
 useEffect(()=>{if(!playing)return;const timer=window.setInterval(()=>{if(!document.hidden)setTime(t=>Math.min(18000,t+100))},100);return()=>clearInterval(timer)},[playing]);
 useEffect(()=>{if(time>=18000)setPlaying(false)},[time]);
 useEffect(()=>{const observer=new IntersectionObserver(([entry])=>{if(!entry.isIntersecting)setPlaying(false)});if(host.current)observer.observe(host.current);return()=>observer.disconnect()},[]);
 const replay=()=>{setTime(0);setCollection(100);setSelected('C-101');setTab('clients');setChecks([true,true,true,false,false]);setPlaying(!reduced)};
 const download=()=>{const csv='\uFEFF'+(en?'ID,Type,Name,Total,Paid,Open balance,Overdue (K ILS)':'מזהה,סוג,שם,סך חיובים,שולם,יתרה פתוחה,באיחור (אלפי שח)')+'\n'+records.map(r=>`${r.id},${r.type},${r[lang]},${r.total},${r.paid},${r.total-r.paid},${r.late}`).join('\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='ai-finance-month-close-demo.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
 return <section ref={host} className="af-section af-finance-moment af-studio" aria-labelledby="finance-moment-title"><div className="af-wrap">
  <div className="af-section-heading"><div><div className="af-label">AI FINANCE STUDIO</div><h2 id="finance-moment-title">{en?'Close the month.\nSee the whole picture.':'סוגרים חודש.\nרואים את התמונה.'}</h2></div><div><p>{en?'Customers, suppliers and cash flow in one view. Select a balance, test collections and complete the close checklist.':'לקוחות, ספקים ותזרים בתמונה אחת. בחרו יתרה, שנו את תרחיש הגבייה והתקדמו ברשימת הסגירה.'}</p><small>{en?'Scripted simulation with fictional data. No live AI or client information.':'הדמיה מתוכננת עם נתונים בדויים. ללא הפעלת AI בזמן אמת או מידע של לקוחות.'}</small></div></div>
  <div className="af-studio-window">
   <div className="af-studio-top"><span><Bot size={23}/> AI FINANCE <b>STUDIO</b></span><span className="af-studio-badge">{en?'MONTH-END · DEMO':'סגירת חודש · הדגמה'}</span></div>
   <div className="af-studio-controls"><button className="af-studio-play" onClick={()=>{if(time>=18000)replay();else if(reduced)setTime(starts[Math.min(stage+1,3)]);else setPlaying(!playing)}}>{playing?<Pause size={18}/>:<Play size={18}/>} {playing?(en?'Pause':'עצירה'):time>=18000?(en?'Watch it being built':'צפו בתהליך הבנייה'):reduced?(en?'Next step':'לשלב הבא'):(en?'Continue':'המשך')}</button><button onClick={replay} aria-label={en?'Start again':'מההתחלה'}><RotateCcw size={19}/></button><button onClick={download}><Download size={18}/><span>{en?'Source data':'נתוני המקור'}</span></button><span className="af-studio-time">{en?'18-second walkthrough':'התהליך ב־18 שניות'}</span></div>
   <nav className="af-studio-steps" aria-label={en?'Demo stages':'שלבי ההדגמה'}>{labels.map((label,i)=><button key={label} onClick={()=>{setPlaying(false);setTime(i===0?4000:starts[i]);}} aria-current={stage===i?'step':undefined}><span>{stage>i?<Check size={16}/>:i+1}</span>{label}</button>)}</nav>
   <div className="af-studio-progress" aria-hidden="true"><i style={{width:`${time/180}%`}}/></div>
   <div className="af-studio-request"><Bot size={27}/><div><span>{en?'THE REQUEST':'הבקשה שלנו'}</span><p>{stage===0?prompt.slice(0,Math.floor(prompt.length*Math.min(1,time/3500))):prompt}<i className={playing&&stage===0?'af-studio-caret':''}/></p></div></div>
   {stage<2?<div className="af-studio-building"><div className="af-studio-build-icon"><FileSpreadsheet size={48}/></div><div><h3>{stage===0?(en?'Two ledgers. One clear request.':'שתי כרטסות. בקשה אחת ברורה.'):(en?'Reconcile first. Then analyse.':'קודם מתאימים. אחר כך מנתחים.')}</h3><p>{en?'8 fictional ledger balances · amounts in K ILS':'8 יתרות כרטסת בדויות · סכומים באלפי ש״ח'}</p><ul>{(en?['Read customer and supplier ledgers','Customers: 128 billed − 80 received = 48 open','Suppliers: 94 billed − 60 paid = 34 open','Flag 3 overdue balances for review']:['קריאת כרטסות הלקוחות והספקים','לקוחות: 128 חיובים פחות 80 תקבולים = 48 פתוח','ספקים: 94 חיובים פחות 60 תשלומים = 34 פתוח','סימון 3 יתרות באיחור לבדיקה']).map((text,i)=><li key={text} className={time>=4200+i*1000?'is-ready':''}><Check size={18}/>{text}</li>)}</ul></div></div>:<div className="af-studio-dashboard">
    <div className="af-studio-report-heading"><div><span>{en?'MONTH-END CONTROL ROOM':'חדר הבקרה של סוף החודש'}</span><h3>{en?'Every balance has a next step.':'לכל יתרה יש צעד הבא.'}</h3></div><span className="af-studio-verified"><ShieldCheck size={17}/>{en?'Source totals reconciled':'סכומי המקור תואמים'}</span></div>
    <div className="af-studio-kpis"><div><span>{en?'Receivables':'לקוחות לגבייה'}</span><strong>{receivables}<small>{en?'K ILS · 4 customers':'אלף ש״ח · 4 לקוחות'}</small></strong></div><div><span>{en?'Payables':'ספקים לתשלום'}</span><strong>{payables}<small>{en?'K ILS · 4 suppliers':'אלף ש״ח · 4 ספקים'}</small></strong></div><div className="af-studio-kpi-alert"><span>{en?'Net cash flow · scenario':'תזרים נטו · תרחיש'}</span><strong><bdi>{net>0?'+':''}{f(net)}</bdi><small>{en?'K ILS · selected balances only':'אלף ש״ח · היתרות שנבחרו בלבד'}</small></strong></div></div>
    <div className="af-studio-ledger-tabs" role="group" aria-label={en?'Choose ledger':'בחירת כרטסת'}>{['clients','suppliers'].map(type=><button key={type} aria-pressed={tab===type} onClick={()=>{setTab(type);setSelected(type==='clients'?'C-101':'S-201')}}>{type==='clients'?(en?'Customers':'לקוחות'):(en?'Suppliers':'ספקים')}<span>04</span></button>)}<span>{en?'3 overdue balances':'3 יתרות באיחור'}</span></div>
    <div className="af-studio-analysis"><div className="af-studio-chart"><div className="af-studio-chart-title"><h4><ChartNoAxesCombined size={20}/>{en?'Paid and outstanding':'שולם ונותר פתוח'}</h4><span><i/>{en?'Paid':'שולם'}<i/>{en?'Open':'פתוח'}</span></div><p>{en?'Select a balance to inspect its source. K ILS.':'לחצו על יתרה כדי לפתוח את המקור. באלפי ש״ח.'}</p>{visible.map(r=><button key={r.id} className={selected===r.id?'is-selected':''} aria-pressed={selected===r.id} onClick={()=>setSelected(r.id)}><span>{r[lang]}{r.late&&<small className="af-studio-overdue">{en?'Overdue':'באיחור'}</small>}</span><div className="af-studio-bars"><i style={{width:`${r.paid/48*100}%`}}/><i style={{width:`${(r.total-r.paid)/48*100}%`}}/></div><bdi>{r.total-r.paid}</bdi></button>)}</div>
    <aside className="af-studio-insight"><span><Search size={18}/>{en?'FOLLOW THE BALANCE':'מה עומד מאחורי היתרה'}</span><h4>{focus[lang]}</h4><dl><div><dt>{en?'Total charges':'סך חיובים'}</dt><dd>{focus.total}</dd></div><div><dt>{en?'Paid / received':'שולם / התקבל'}</dt><dd>{focus.paid}</dd></div><div><dt>{en?'Open balance':'יתרה פתוחה'}</dt><dd>{focus.total-focus.paid}</dd></div></dl><small>{en?`Source: ${focus.id} · CSV row ${records.indexOf(focus)+2} · K ILS`:`מקור: ${focus.id} · שורה ${records.indexOf(focus)+2} בקובץ · אלפי ש״ח`}</small><p>{focus.late?(en?'Past the agreed payment date. Check disputed amounts, unapplied payments and the next action with the account owner.':'היתרה עברה את מועד התשלום. צריך לבדוק סכומים במחלוקת, תשלומים שטרם שויכו ואת הצעד הבא עם האחראים לכרטסת.'):(en?'Not flagged overdue in this example. Confirm the due date and supporting documents before closing.':'היתרה אינה מסומנת באיחור בדוגמה. לפני הסגירה, יש לאמת את מועד התשלום ואת המסמכים התומכים.')}</p></aside></div>
    {stage===3&&<><div className="af-studio-scenario"><div><span>{en?'TEST THE CASH FLOW':'בודקים את התזרים'}</span><h4>{en?'What if not every customer pays?':'מה יקרה אם לא כל הלקוחות ישלמו?'}</h4><p>{en?'Assume all 34K of payables are paid. Change the share collected from the 48K receivables. This is net movement, not the bank balance.':'בהנחה שכל 34 אלף השקלים לספקים ישולמו, שנו את שיעור הגבייה מתוך 48 אלף השקלים של הלקוחות. זו תנועה נטו, לא יתרת הבנק.'}</p></div><div><label htmlFor="demo-collection">{en?'Collection rate':'שיעור גבייה בתרחיש'}<strong>{collection}%</strong></label><input id="demo-collection" type="range" min="0" max="100" step="5" value={collection} onChange={e=>setCollection(Number(e.target.value))} aria-valuetext={`${collection}%`}/><div className="af-studio-range-labels"><span>0%</span><span>100%</span></div><p className="af-studio-scenario-result" aria-live="polite">{en?'Receipts':'תקבולים'}: {f(collected)} · {en?'Net':'נטו'}: <bdi>{net>0?'+':''}{f(net)}</bdi> {en?'K ILS':'אלף ש״ח'}</p></div></div>
    <div className="af-studio-close"><div><span>{en?'CLOSE CHECKLIST · SIMULATION':'רשימת סגירה · הדמיה'}</span><h4>{en?'From insight to a checked task.':'מתובנה למשימה שנבדקה.'}</h4><strong>{progress}%</strong><div className="af-studio-close-progress"><i style={{width:`${progress}%`}}/></div><p>{en?'Complete the two review tasks to see the demo checklist reach 100%. No real approval or posting takes place.':'סמנו את שתי משימות הבדיקה כדי להשלים את הרשימה בהדמיה. לא מתבצעים אישור או רישום אמיתיים.'}</p></div><div>{tasks.map((task,i)=><label key={task}><input type="checkbox" checked={checks[i]} onChange={e=>setChecks(values=>values.map((v,n)=>n===i?e.target.checked:v))}/><span>{task}</span>{i<3&&<small>{en?'Data check':'בדיקת נתונים'}</small>}</label>)}</div></div></>}
    <div className="af-studio-takeaway"><ShieldCheck size={22}/><p>{en?'Trace the balance, understand the exception and assign the next action. The final decision stays with people.':'עוקבים אחרי היתרה, מבינים את החריג ומגדירים את הפעולה הבאה. ההחלטה נשארת אצל האנשים.'}</p><ArrowUpRight size={22}/></div>
   </div>}
  </div>
 </div></section>
}
